version: '3.8'

services:
  web:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && gunicorn app.config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - app_network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge