services:
  - type: web
    name: portal-grs-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations
    startCommand: python manage.py migrate && gunicorn app.config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.config.settings.production
      - key: SECRET_KEY
        value: "django-insecure-9e645a25d7f8b36b3fe2f698b52c67a13e984fe572f130fe"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_NAME
        value: db_portal_grs
      - key: DB_USER
        value: db_portal_grs_user
      - key: DB_PASSWORD
        value: cnyUojVJ7VMJR7DUsehHHYrXCfCtJl4H
      - key: DB_HOST
        value: dpg-cvakmnnnoe9s73faum7g-a
    plan: starter