# Generated by Django 4.2.8 on 2025-03-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('normal', 'Usuário Normal')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('ultima_sessao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('rota_frontend', models.CharField(blank=True, max_length=200, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('permissoes_disponiveis', models.JSONField(default=dict)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tela',
                'verbose_name_plural': 'Telas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='AcessoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissoes', models.JSONField(default=dict)),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telas_concedidas', to=settings.AUTH_USER_MODEL)),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.tela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a Tela',
                'verbose_name_plural': 'Acessos a Telas',
                'unique_together': {('usuario', 'tela')},
            },
        ),
        migrations.CreateModel(
            name='AcessoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_concedidos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a Empresa',
                'verbose_name_plural': 'Acessos a Empresas',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='acesso_empresas',
            field=models.ManyToManyField(related_name='usuarios_com_acesso', through='autenticacao.AcessoEmpresa', to='autenticacao.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acesso_telas',
            field=models.ManyToManyField(related_name='usuarios_com_acesso', through='autenticacao.AcessoTela', to='autenticacao.tela'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_principais', to='autenticacao.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
