# Generated by Django 4.2.8 on 2025-03-15 09:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('nome_abreviado', models.CharField(max_length=60)),
                ('razao_social', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=110)),
                ('numero_endereco', models.CharField(max_length=20)),
                ('complemento_endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-\\d{3}$')])),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_abreviado'],
            },
        ),
        migrations.CreateModel(
            name='TipoAbsenteismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('requer_atestado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Absenteísmo',
                'verbose_name_plural': 'Tipos de Absenteísmo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoConvocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Convocação',
                'verbose_name_plural': 'Tipos de Convocação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=19, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Feminino')], null=True)),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Separado(a)'), (4, 'Desquitado(a)'), (5, 'Viúvo(a)'), (6, 'Outros'), (7, 'Divorciado(a)')], null=True)),
                ('matricula_funcionario', models.CharField(blank=True, max_length=30, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado')], max_length=20)),
                ('codigo_unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_unidade', models.CharField(blank=True, max_length=130, null=True)),
                ('codigo_setor', models.CharField(blank=True, max_length=12, null=True)),
                ('nome_setor', models.CharField(blank=True, max_length=130, null=True)),
                ('codigo_cargo', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_cargo', models.CharField(blank=True, max_length=130, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Convocacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_convocacao', models.DateField()),
                ('data_limite_resposta', models.DateField()),
                ('respondido', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.CharField(choices=[('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='core.funcionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocacoes', to='core.tipoconvocacao')),
            ],
            options={
                'verbose_name': 'Convocação',
                'verbose_name_plural': 'Convocações',
                'ordering': ['-data_convocacao'],
            },
        ),
        migrations.CreateModel(
            name='Absenteismo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('possui_atestado', models.BooleanField(default=False)),
                ('atestado', models.FileField(blank=True, null=True, upload_to='atestados/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absenteismos_registrados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteismos', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteismos', to='core.funcionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absenteismos', to='core.tipoabsenteismo')),
            ],
            options={
                'verbose_name': 'Absenteísmo',
                'verbose_name_plural': 'Absenteísmos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
